- name: Update apt cache & upgrade packages
  apt:
      update_cache: yes
      upgrade: dist

- name: Install common utilities
  apt:
      name:
        - curl
        - vim
        - git
        - unzip
        - htop
      state: present

- name: Install & enable fail2ban
  apt:
      name: fail2ban
      state: present

- name: Ensure UFW is installed and SSH allowed
  apt:
      name: ufw
      state: present

- ufw:
      rule: allow
      port: 22
      proto: tcp

- name: Enable UFW
  ufw:
      state: enabled
      policy: deny
      direction: incoming
