# ~/ansible-cm/setup.yml
---
- name: Configure AWS EC2 server
  hosts: web
  become: yes

  roles:
     - { role: base,  tags: base }
     - { role: nginx, tags: nginx }
     - { role: app,   tags: app }
     - { role: ssh,   tags: ssh }
